name: Build java application
description: Checks out the repository, build gradle application.

on:
  push:
  pull_request:

jobs:
  build_application:
    container: node:16
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - run: ./gradlew build
      - run: dir
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build/libs